name: test-action

on:
  # push:
  #   branches: [master]
  #   # IMPORTANT: Avoids endless loop
  #   paths-ignore:
  #     - "README.md"
  workflow_dispatch:
    inputs:
      src_repository:
        description: Source Repository - {owner}/{repo_name}
        required: true
      src_workflow_name:
        description: Source Workflow Name
        required: true
      src_sha:
        description: Source Repository SHA - GITHUB_SHA
        required: true

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test Action
    env:
      SRC_REPOSITORY: ${{ github.event.inputs.src_repository }}
      SRC_WORKFLOW_NAME: ${{ github.event.inputs.src_workflow_name }}
      SRC_SHA: ${{ github.event.inputs.src_sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Source File
        run: |
          echo "<div>$(whoami) - $(date)</div>" > test_results.log
      - uses: unfor19/replacer-action@master
        name: Update README.md file
        with:
          src-file-path: "test_results.log"
          dst-file-path: "README.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-user-name: "replacer-action"
          git-user-email: "replacer-action@meirg.co.il"
          git-commit-msg: "Updated by GitHub Actions"
          git-skip-commit: false
          git-skip-push: false
          create-backup: true
      - name: Success - Update Source Repository Status Check
        if: success()
        run: |
          curl --fail -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${SRC_REPOSITORY}/statuses/${SRC_SHA}" \
            -d '{"state":"state", "context": "test-action", "description": "Status update for '"${SRC_REPOSITORY}"'", "target_url": "https://github.com/'${GITHUB_REPOSITORY}'/actions/runs/'"${GITHUB_RUN_ID}"'"}'
      - name: Failed - Update Source Repository Status Check
        if: failure()
        run: |
          curl --fail -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${SRC_REPOSITORY}/statuses/${SRC_SHA}" \
            -d '{"state":"failed", "context": "test-action", "description": "Status update for '"${SRC_REPOSITORY}"'", "target_url": "https://github.com/'${GITHUB_REPOSITORY}'/actions/runs/'"${GITHUB_RUN_ID}"'"}'
