name: test-action

on:
  push:
    branches: [master]
    # IMPORTANT: Avoids endless loop
    paths-ignore:
      - "README.md"
  workflow_dispatch:
    inputs:
      src_workflow_name:
        description: Source Workflow Name
        required: false
        default: ""
      src_workflow_run_id:
        description: Source Workflow Run ID
        required: false
        default: -1

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test Action
    env:
      SRC_WORKFLOW_NAME: ${{ github.event.inputs.src_workflow_name }}
      SRC_WORKFLOW_RUN_ID: ${{ github.event.inputs.src_workflow_run_id }}
    steps:
      - uses: actions/checkout@v2
      - name: Prints Workflow Inputs
        run: |
          echo "$SRC_WORKFLOW_NAME"
          echo "$SRC_WORKFLOW_RUN_ID"
      - name: Prepare Source File
        run: |
          echo "<div>$(whoami) - $(date)</div>" > test_results.log
      - uses: unfor19/replacer-action@master
        name: Update README.md file
        with:
          src-file-path: "test_results.log"
          dst-file-path: "README.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-user-name: "replacer-action"
          git-user-email: "replacer-action@meirg.co.il"
          git-commit-msg: "Updated by GitHub Actions"
          git-skip-commit: false
          git-skip-push: false
          create-backup: true
